name: release

on:
  release:
    types:
      [published, edited]
    tags:
      - 'release/v*' # only release a versioned tag, such as v.X.Y.Z

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install
        run: pip install pipenv

      - name: Build dist
        run: pipenv run python setup.py sdist bdist_wheel

      - name: Run tests
        run: make test


